### ISSUE TITLE
restore with password not working

### ISSUE THREAD

**Issue by tmalatinszki** [naval/mysql-tools#1]
Hi,

In case of database restore with password the value of password attribute is not injected into the command. The root cause of the issue is the `options.password` is missing from the command builder (96. line), so instead of password the database name will appear in the generated command.

How it is looks like now:

```
command = util.format('mysql -h %s -u %s -p%s %s <%s', options.host, options.user, options.database, options.sqlFilePath);
```

How should it look like:

```
command = util.format('mysql -h %s -u %s -p%s %s <%s', options.host, options.user, options.password, options.database, options.sqlFilePath);
```

Regards,
Tamás

**Comment by naval** [comment]
Thanks for report a bug

**Comment by naval** [comment]
I have fixed password issue

**Comment by tmalatinszki** [comment]
Thanks Naval, it is working fine now!

Regards,
Tamás
